#Study.nct_id = primaryIdentifier
Study.ctis_id = primaryIdentifier
Study.nct_id = nctID
Study.euctr_id = euctrID
StudyCountry.key = study,country,countryName

StudyObject.key = linkedStudy,type,accessUrl

Country.key = isoAlpha2