DataSet.key = name
DataSource.key = name

Study.key = primaryIdentifier

StudyIdentifier.key = study,value
StudyCountry.key = study,country,countryName
StudyCondition.key = term
Intervention.key = type,name

# StudyObject.key = linkedStudy,type,accessUrl

Country.key = isoAlpha2