DataSet.key = name
DataSource.key = name

Study.ctis_id = primaryIdentifier
Study.nct_id = nctID
Study.euctr_id = euctrID

StudyCountry.key = study,country,countryName
StudyCondition.key = study,originalValue

StudyObject.key = linkedStudy,type,accessUrl

Country.key=isoAlpha2
