# Study.euctr_id = primaryIdentifier
Study.euctr_id = euctrID
StudyCountry.key = study,country,countryName
StudyCondition.key = study,originalValue

StudyObject.key = linkedStudy,type,accessUrl

Country.key=isoAlpha2